package ladder.dao;

import java.util.List;
import ladder.dao.model.MatchResult;
import ladder.dao.model.MatchResultExample;
import org.apache.ibatis.annotations.Param;

public interface MatchResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_result
     *
     * @mbg.generated
     */
    long countByExample(MatchResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_result
     *
     * @mbg.generated
     */
    int deleteByExample(MatchResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_result
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_result
     *
     * @mbg.generated
     */
    int insert(MatchResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_result
     *
     * @mbg.generated
     */
    int insertSelective(MatchResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_result
     *
     * @mbg.generated
     */
    List<MatchResult> selectByExample(MatchResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_result
     *
     * @mbg.generated
     */
    MatchResult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_result
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MatchResult record, @Param("example") MatchResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_result
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MatchResult record, @Param("example") MatchResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MatchResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MatchResult record);
}