package ladder.dao;

import java.util.List;
import ladder.dao.model.MatchPool;
import ladder.dao.model.MatchPoolExample;
import org.apache.ibatis.annotations.Param;

public interface MatchPoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    long countByExample(MatchPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    int deleteByExample(MatchPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    int insert(MatchPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    int insertSelective(MatchPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    List<MatchPool> selectByExample(MatchPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    MatchPool selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MatchPool record, @Param("example") MatchPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MatchPool record, @Param("example") MatchPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MatchPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MatchPool record);
}