package ladder.dao.model;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.bot_name
     *
     * @mbg.generated
     */
    private String botName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.bot_type
     *
     * @mbg.generated
     */
    private Integer botType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.race
     *
     * @mbg.generated
     */
    private Integer race;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.bot_path
     *
     * @mbg.generated
     */
    private String botPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.email
     *
     * @return the value of account.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.email
     *
     * @param email the value for account.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.username
     *
     * @return the value of account.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.username
     *
     * @param username the value for account.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.bot_name
     *
     * @return the value of account.bot_name
     *
     * @mbg.generated
     */
    public String getBotName() {
        return botName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.bot_name
     *
     * @param botName the value for account.bot_name
     *
     * @mbg.generated
     */
    public void setBotName(String botName) {
        this.botName = botName == null ? null : botName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.bot_type
     *
     * @return the value of account.bot_type
     *
     * @mbg.generated
     */
    public Integer getBotType() {
        return botType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.bot_type
     *
     * @param botType the value for account.bot_type
     *
     * @mbg.generated
     */
    public void setBotType(Integer botType) {
        this.botType = botType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.race
     *
     * @return the value of account.race
     *
     * @mbg.generated
     */
    public Integer getRace() {
        return race;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.race
     *
     * @param race the value for account.race
     *
     * @mbg.generated
     */
    public void setRace(Integer race) {
        this.race = race;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.description
     *
     * @return the value of account.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.description
     *
     * @param description the value for account.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.bot_path
     *
     * @return the value of account.bot_path
     *
     * @mbg.generated
     */
    public String getBotPath() {
        return botPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.bot_path
     *
     * @param botPath the value for account.bot_path
     *
     * @mbg.generated
     */
    public void setBotPath(String botPath) {
        this.botPath = botPath == null ? null : botPath.trim();
    }
}