package ladder.dao.model;

public class MatchResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_result.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_result.bot_name_A
     *
     * @mbg.generated
     */
    private String botNameA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_result.bot_name_B
     *
     * @mbg.generated
     */
    private String botNameB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_result.win
     *
     * @mbg.generated
     */
    private Integer win;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_result.replay_path
     *
     * @mbg.generated
     */
    private String replayPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_result.id
     *
     * @return the value of match_result.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_result.id
     *
     * @param id the value for match_result.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_result.bot_name_A
     *
     * @return the value of match_result.bot_name_A
     *
     * @mbg.generated
     */
    public String getBotNameA() {
        return botNameA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_result.bot_name_A
     *
     * @param botNameA the value for match_result.bot_name_A
     *
     * @mbg.generated
     */
    public void setBotNameA(String botNameA) {
        this.botNameA = botNameA == null ? null : botNameA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_result.bot_name_B
     *
     * @return the value of match_result.bot_name_B
     *
     * @mbg.generated
     */
    public String getBotNameB() {
        return botNameB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_result.bot_name_B
     *
     * @param botNameB the value for match_result.bot_name_B
     *
     * @mbg.generated
     */
    public void setBotNameB(String botNameB) {
        this.botNameB = botNameB == null ? null : botNameB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_result.win
     *
     * @return the value of match_result.win
     *
     * @mbg.generated
     */
    public Integer getWin() {
        return win;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_result.win
     *
     * @param win the value for match_result.win
     *
     * @mbg.generated
     */
    public void setWin(Integer win) {
        this.win = win;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_result.replay_path
     *
     * @return the value of match_result.replay_path
     *
     * @mbg.generated
     */
    public String getReplayPath() {
        return replayPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_result.replay_path
     *
     * @param replayPath the value for match_result.replay_path
     *
     * @mbg.generated
     */
    public void setReplayPath(String replayPath) {
        this.replayPath = replayPath == null ? null : replayPath.trim();
    }
}