package ladder.dao.model;

import java.util.ArrayList;
import java.util.List;

public class MatchPoolExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    public MatchPoolExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andBotNameIsNull() {
            addCriterion("bot_name is null");
            return (Criteria) this;
        }

        public Criteria andBotNameIsNotNull() {
            addCriterion("bot_name is not null");
            return (Criteria) this;
        }

        public Criteria andBotNameEqualTo(String value) {
            addCriterion("bot_name =", value, "botName");
            return (Criteria) this;
        }

        public Criteria andBotNameNotEqualTo(String value) {
            addCriterion("bot_name <>", value, "botName");
            return (Criteria) this;
        }

        public Criteria andBotNameGreaterThan(String value) {
            addCriterion("bot_name >", value, "botName");
            return (Criteria) this;
        }

        public Criteria andBotNameGreaterThanOrEqualTo(String value) {
            addCriterion("bot_name >=", value, "botName");
            return (Criteria) this;
        }

        public Criteria andBotNameLessThan(String value) {
            addCriterion("bot_name <", value, "botName");
            return (Criteria) this;
        }

        public Criteria andBotNameLessThanOrEqualTo(String value) {
            addCriterion("bot_name <=", value, "botName");
            return (Criteria) this;
        }

        public Criteria andBotNameLike(String value) {
            addCriterion("bot_name like", value, "botName");
            return (Criteria) this;
        }

        public Criteria andBotNameNotLike(String value) {
            addCriterion("bot_name not like", value, "botName");
            return (Criteria) this;
        }

        public Criteria andBotNameIn(List<String> values) {
            addCriterion("bot_name in", values, "botName");
            return (Criteria) this;
        }

        public Criteria andBotNameNotIn(List<String> values) {
            addCriterion("bot_name not in", values, "botName");
            return (Criteria) this;
        }

        public Criteria andBotNameBetween(String value1, String value2) {
            addCriterion("bot_name between", value1, value2, "botName");
            return (Criteria) this;
        }

        public Criteria andBotNameNotBetween(String value1, String value2) {
            addCriterion("bot_name not between", value1, value2, "botName");
            return (Criteria) this;
        }

        public Criteria andBotPathIsNull() {
            addCriterion("bot_path is null");
            return (Criteria) this;
        }

        public Criteria andBotPathIsNotNull() {
            addCriterion("bot_path is not null");
            return (Criteria) this;
        }

        public Criteria andBotPathEqualTo(String value) {
            addCriterion("bot_path =", value, "botPath");
            return (Criteria) this;
        }

        public Criteria andBotPathNotEqualTo(String value) {
            addCriterion("bot_path <>", value, "botPath");
            return (Criteria) this;
        }

        public Criteria andBotPathGreaterThan(String value) {
            addCriterion("bot_path >", value, "botPath");
            return (Criteria) this;
        }

        public Criteria andBotPathGreaterThanOrEqualTo(String value) {
            addCriterion("bot_path >=", value, "botPath");
            return (Criteria) this;
        }

        public Criteria andBotPathLessThan(String value) {
            addCriterion("bot_path <", value, "botPath");
            return (Criteria) this;
        }

        public Criteria andBotPathLessThanOrEqualTo(String value) {
            addCriterion("bot_path <=", value, "botPath");
            return (Criteria) this;
        }

        public Criteria andBotPathLike(String value) {
            addCriterion("bot_path like", value, "botPath");
            return (Criteria) this;
        }

        public Criteria andBotPathNotLike(String value) {
            addCriterion("bot_path not like", value, "botPath");
            return (Criteria) this;
        }

        public Criteria andBotPathIn(List<String> values) {
            addCriterion("bot_path in", values, "botPath");
            return (Criteria) this;
        }

        public Criteria andBotPathNotIn(List<String> values) {
            addCriterion("bot_path not in", values, "botPath");
            return (Criteria) this;
        }

        public Criteria andBotPathBetween(String value1, String value2) {
            addCriterion("bot_path between", value1, value2, "botPath");
            return (Criteria) this;
        }

        public Criteria andBotPathNotBetween(String value1, String value2) {
            addCriterion("bot_path not between", value1, value2, "botPath");
            return (Criteria) this;
        }

        public Criteria andConfigPathIsNull() {
            addCriterion("config_path is null");
            return (Criteria) this;
        }

        public Criteria andConfigPathIsNotNull() {
            addCriterion("config_path is not null");
            return (Criteria) this;
        }

        public Criteria andConfigPathEqualTo(String value) {
            addCriterion("config_path =", value, "configPath");
            return (Criteria) this;
        }

        public Criteria andConfigPathNotEqualTo(String value) {
            addCriterion("config_path <>", value, "configPath");
            return (Criteria) this;
        }

        public Criteria andConfigPathGreaterThan(String value) {
            addCriterion("config_path >", value, "configPath");
            return (Criteria) this;
        }

        public Criteria andConfigPathGreaterThanOrEqualTo(String value) {
            addCriterion("config_path >=", value, "configPath");
            return (Criteria) this;
        }

        public Criteria andConfigPathLessThan(String value) {
            addCriterion("config_path <", value, "configPath");
            return (Criteria) this;
        }

        public Criteria andConfigPathLessThanOrEqualTo(String value) {
            addCriterion("config_path <=", value, "configPath");
            return (Criteria) this;
        }

        public Criteria andConfigPathLike(String value) {
            addCriterion("config_path like", value, "configPath");
            return (Criteria) this;
        }

        public Criteria andConfigPathNotLike(String value) {
            addCriterion("config_path not like", value, "configPath");
            return (Criteria) this;
        }

        public Criteria andConfigPathIn(List<String> values) {
            addCriterion("config_path in", values, "configPath");
            return (Criteria) this;
        }

        public Criteria andConfigPathNotIn(List<String> values) {
            addCriterion("config_path not in", values, "configPath");
            return (Criteria) this;
        }

        public Criteria andConfigPathBetween(String value1, String value2) {
            addCriterion("config_path between", value1, value2, "configPath");
            return (Criteria) this;
        }

        public Criteria andConfigPathNotBetween(String value1, String value2) {
            addCriterion("config_path not between", value1, value2, "configPath");
            return (Criteria) this;
        }

        public Criteria andInMatchIsNull() {
            addCriterion("in_match is null");
            return (Criteria) this;
        }

        public Criteria andInMatchIsNotNull() {
            addCriterion("in_match is not null");
            return (Criteria) this;
        }

        public Criteria andInMatchEqualTo(Boolean value) {
            addCriterion("in_match =", value, "inMatch");
            return (Criteria) this;
        }

        public Criteria andInMatchNotEqualTo(Boolean value) {
            addCriterion("in_match <>", value, "inMatch");
            return (Criteria) this;
        }

        public Criteria andInMatchGreaterThan(Boolean value) {
            addCriterion("in_match >", value, "inMatch");
            return (Criteria) this;
        }

        public Criteria andInMatchGreaterThanOrEqualTo(Boolean value) {
            addCriterion("in_match >=", value, "inMatch");
            return (Criteria) this;
        }

        public Criteria andInMatchLessThan(Boolean value) {
            addCriterion("in_match <", value, "inMatch");
            return (Criteria) this;
        }

        public Criteria andInMatchLessThanOrEqualTo(Boolean value) {
            addCriterion("in_match <=", value, "inMatch");
            return (Criteria) this;
        }

        public Criteria andInMatchIn(List<Boolean> values) {
            addCriterion("in_match in", values, "inMatch");
            return (Criteria) this;
        }

        public Criteria andInMatchNotIn(List<Boolean> values) {
            addCriterion("in_match not in", values, "inMatch");
            return (Criteria) this;
        }

        public Criteria andInMatchBetween(Boolean value1, Boolean value2) {
            addCriterion("in_match between", value1, value2, "inMatch");
            return (Criteria) this;
        }

        public Criteria andInMatchNotBetween(Boolean value1, Boolean value2) {
            addCriterion("in_match not between", value1, value2, "inMatch");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table match_pool
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table match_pool
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}