package ladder.dao.model;

public class MatchPool {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_pool.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_pool.bot_name
     *
     * @mbg.generated
     */
    private String botName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_pool.bot_path
     *
     * @mbg.generated
     */
    private String botPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_pool.in_match
     *
     * @mbg.generated
     */
    private Boolean inMatch;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_pool.username
     *
     * @return the value of match_pool.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_pool.username
     *
     * @param username the value for match_pool.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_pool.bot_name
     *
     * @return the value of match_pool.bot_name
     *
     * @mbg.generated
     */
    public String getBotName() {
        return botName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_pool.bot_name
     *
     * @param botName the value for match_pool.bot_name
     *
     * @mbg.generated
     */
    public void setBotName(String botName) {
        this.botName = botName == null ? null : botName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_pool.bot_path
     *
     * @return the value of match_pool.bot_path
     *
     * @mbg.generated
     */
    public String getBotPath() {
        return botPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_pool.bot_path
     *
     * @param botPath the value for match_pool.bot_path
     *
     * @mbg.generated
     */
    public void setBotPath(String botPath) {
        this.botPath = botPath == null ? null : botPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_pool.in_match
     *
     * @return the value of match_pool.in_match
     *
     * @mbg.generated
     */
    public Boolean getInMatch() {
        return inMatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_pool.in_match
     *
     * @param inMatch the value for match_pool.in_match
     *
     * @mbg.generated
     */
    public void setInMatch(Boolean inMatch) {
        this.inMatch = inMatch;
    }
}