/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ladder_service_MatchService */

#ifndef _Included_ladder_service_MatchService
#define _Included_ladder_service_MatchService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ladder_service_MatchService
 * Method:    match
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ladder_service_MatchService_match
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
